language: java

jdk:
- oraclejdk8
- openjdk8

after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: simple-http

cache:
  directories:
    - '$HOME/.sonar/cache'
    
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
